### PR TITLE
Figure S7: Add new panels A and C

### LINKED ISSUE #1694: Figure S7 panel: Barplot across RNA library and cancer groups
From #1691, we're going to be updating Figure S7 with some new panels.
This issue will track this panel:

> (A) a bar plot showing distributions of disease type (cancer_group_display), broken up by library prep strategy (RNA_library) – the objective is to illustrate that disease type is unbalanced between poly-A and stranded datasets, so whatever bar plot strategy we think best communicates this works.

Noting with this new panel A, the previous panel A becomes D.

### LINKED ISSUE #1696: Figure S7: Include sequencing center UMAP
From #1691, we're going to be updating Figure S7 with some new panels.
This issue will track this panel:

> (C) the UMAP plot highlighting sequencing center: https://alexslemonade.github.io/OpenPBTA-analysis/analyses/transcriptomic-dimension-reduction/04-explore-sequencing-center-effects.nb.html#cancer_group_umap

This panel already was made in the linked notebook above, so the steps that need to happen here are:
- Export that panel in the notebook/module where it currently lives
- Add a line in `figures/generate-figures.sh` to copy it over: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/627ec427ad0a8d9d913e614c9db50546c56d8283/figures/generate-figures.sh#L188-L210

### PR DESCRIPTION
**Pull request by sjspielman**
Part of #1691

Closes #1694 
Closes #1696 

This PR adds two panels for Figure S7 and updates some of the existing scaffoldings, as follows:

1. Add new a panel A with the script [`figures/scripts/figS7-seqcenter-barplot.R`](https://github.com/sjspielman/OpenPBTA-analysis/blob/5b8c109e496bf153cd9d1812e9fff7924788db66/figures/scripts/figS7-seqcenter-barplot.R).
    - This script exports the panel [`figures/pdfs/supp/figs7/panels/RNA_library_barplot.pdf`](figures/pdfs/supp/figs7/panels/RNA_library_barplot.pdf) for use in the supplementary figure. 
    - This script was also recorded in `figures/scripts/README.md`.
2. Update the notebook `analyses/transcriptomic-dimension-reduction/04-explore-sequencing-center-effects.Rmd` to _export_ the relevant plot needed for panel C.
    - Plot is exported to [`analyses/transcriptomic-dimension-reduction/plots/umap_cancer-group_sequencing-center.pdf`](https://github.com/sjspielman/OpenPBTA-analysis/blob/5b8c109e496bf153cd9d1812e9fff7924788db66/analyses/transcriptomic-dimension-reduction/plots/umap_cancer-group_sequencing-center.pdf). 
    - This also involved some minor code tweaks for pub-ready plot styling. The notebook was rerun, and the module `README.md` was updated to note this exported plot.
3. `figures/generate-figures.sh` was updated as follows:
    - Run the new `figures/scripts/figS7-seqcenter-barplot.R` script
    - Copy the UMAP panel into [`figures/pdfs/supp/figS7/panels`](https://github.com/sjspielman/OpenPBTA-analysis/blob/5b8c109e496bf153cd9d1812e9fff7924788db66/figures/pdfs/supp/figs7/panels/umap_cancer-group_sequencing-center.pdf).
    - Update comments to indicate new panel order

### CODE REVIEW

**Comment by sjspielman** [comment]
Noting I'm requesting review from @jaclyn-taroni which can alternatively be interpreted as requesting @jaclyn-taroni to request someone else! :)

File: figures/scripts/figS7-seqcenter-barplot.R [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+pal_colors <- rev(binary_pal_df$hex_codes[binary_pal_df$color_names != "na_color"])
+
+###### Make the plot --------------------------
+
+rna_library_barplot <- ggplot(library_cancer_group_df) +
+  aes(x = cancer_group_display,
+      fill = RNA_library) +
+  geom_bar(color = "black",
+           size = 0.25,
+           alpha = 0.8) +
```
Comment (jashapiro) [inline figures/scripts/figS7-seqcenter-barplot.R:65]: I'm not sure we need/want alpha here, since there is nothing overlapping. 
```suggestion
  geom_bar(color = "black", size = 0.25) +
```

File: figures/scripts/figS7-seqcenter-barplot.R [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+  scale_fill_manual(name = "RNA library preparation",
+                    values = pal_colors) +
+  labs(
+    x = "Cancer group",
+    y = "Total number of participants with RNA-Seq"
+  ) +
+  ggpubr::theme_pubr() +
+  theme(
+    axis.text.x = element_text(angle = 45, hjust = 1, size = 6.5),
```
Comment (jashapiro) [inline figures/scripts/figS7-seqcenter-barplot.R:74]: This might need to be even smaller; the multiline labels get very close and hard to read.

Alternatively, output at a larger size, since this is going to be rescaled anyway.

**Review by jashapiro — COMMENTED** [review]
This looks good, just a couple of minor comments about the barplot formatting and an ordering thing that had me confused for a bit.

File: figures/generate-figures.sh [hunk 3]
```diff
@@ -187,26 +187,34 @@ Rscript --vanilla scripts/figS6-subtype-umap-panels.R
...
-# Panel B: TP53 scores across TP53 status
+# Panel E: TP53 scores across TP53 status
 cp ${analyses_dir}/tp53_nf1_score/results/tumor-purity-threshold/tp53-score-status_tumor-purity-threshold.pdf pdfs/supp/figs7/panels/
 
-# Panel C: TP53 expression across TP53 status
+# Panel F: TP53 expression across TP53 status
 cp ${analyses_dir}/tp53_nf1_score/results/tumor-purity-threshold/tp53-fpkm-status_tumor-purity-threshold.pdf pdfs/supp/figs7/panels/
 
-# Panel E: UMAP highlighting broad histologies
+# Panel H: UMAP highlighting broad histologies
```
[the remark this answers is not in the document]
Comment (sjspielman) [reply figures/generate-figures.sh:214]: > Does panel G script have to run before copying panels around? Just noting the out-of-order which had me wondering why G was "skipped".

No, it doesn't have to be run. The organization throughout this `generate-figures.sh` script is, for each figure, we run all scripts and then copy all other panels not produced by scripts. So, code isn't necessarily run by panel.

**Review by jashapiro — APPROVED** [review]
LGTM!

File: figures/scripts/figS7-seqcenter-barplot.R [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+palette_df <- read_tsv(palette_file)
+binary_pal_df <- read_tsv(binary_pal_file)
+
+# Get the RNA samples and combine with `cancer_group_display` information
+library_cancer_group_df <- metadata_df %>%
+  filter(experimental_strategy == "RNA-Seq") %>%
+  # We want one row per patient here
+  mutate(dup_participant = duplicated(Kids_First_Participant_ID)) %>%
+  filter(!dup_participant) %>%
+  # Keep RNA_library and cancer group for each
```
Comment (jharenza) [inline figures/scripts/figS7-seqcenter-barplot.R:36]: Hi @sjspielman just catching up on this. I think there may be a bug here, which may be due to using participants instead of samples here - can you check out `PT_9S6WMQ92` - this patient has two different events sequenced, one is stranded and one is polyA (medullo). Seems like we capture stranded in the plot but not the polyA. Caught my eye.
